#!/bin/bash
#SBATCH -p icelake,a100cpu
#SBATCH -J sim
#SBATCH -o sim.%j.out
#SBATCH -N 1              	                                # number of nodes 
#SBATCH -n 25             	                                # number of cores 
#SBATCH --time=1:00:00    	                                # time allocation
#SBATCH --mem=64GB         	                                # memory pool for all cores 
date
Rscript egScottCreekStochSim.R
date

